image: mcr.microsoft.com/dotnet/framework/sdk

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet build "dotnetcore-sample.sln" --configuration Release

test_job:
  stage: test
  script:
    - dotnet test "dotnetcore-sample.sln" --configuration Release

  dependencies:
    - build_job

