image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build -c Release
  artifacts:
    paths:
      - dotnetcore-tests/bin/Release/netcoreapp3.1/
    expire_in: 1 day

test:
  stage: test
  script:
    - dotnet test -c Release -o testresults
  artifacts:
    paths:
      - testresults/
