image: bitnami/dotnet-sdk:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    paths:
      - ./**/dotnetcore-sample.dll
    expire_in: 1 day

test:
  stage: test
  script:
    - dotnet add package JUnitTestLogger --version 1.1.0
    - dotnet test --logger "junit"
