image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build -c Release
  artifacts:
    paths:
      - bin/Release/

test:
  stage: test
  script:
    - dotnet test -c Release
