image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build_job:
  stage: build
  script:
    - dotnet build "dotnetcore-sample.sln" --configuration Release
